on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      GITHUB_TOKEN: ${{ secrets.PAT }}
      
    strategy:
      fail-fast: false
      matrix:
        node-version: [14, 15, 16]
        package: ["${{ github.repository }}", "github:${{ github.repository }}", "https://github.com/${{ github.repository }}", "git+https://github.com/${{ github.repository }}", "git://github.com/${{ github.repository }}", "git+ssh://git@github.com/${{ github.repository }}", "git+https://${GITHUB_TOKEN}@github.com/${{ github.repository }}"]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm version

      - run: rm package.json

      - run: npm init -y
      
      # - run: git config --global url."https://${{ secrets.PAT }}@github.com/".insteadOf ssh://git@github.com/

      # - run: git config --global url."https://${{ secrets.PAT }}@github.com/".insteadOf git://github.com/

      - run: npm i ${{ matrix.package }} --save

      - run: cat package.json
