on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        node-version: [14, 15, 16]
        package: ["${{ github.repository }}", "github:${{ github.repository }}", "https://github.com/${{ github.repository }}", "git+https://github.com/${{ github.repository }}", "git://github.com/${{ github.repository }}", "git+ssh://git@github.com/${{ github.repository }}"]

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm version

      - run: rm package.json

      - run: npm init -y

      - run: npm i ${{ matrix.package }} --save

      - run: cat package.json
